sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source utils.sh
- echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- build_image "treehouses/php-apache:latest" arm "treehouses/privatebin"
- build_image "treehouses/php-apache:latest" amd64 "treehouses/privatebin"
- build_image "treehouses/php-apache:latest" arm64 "treehouses/privatebin"
- flag=false
before_deploy:
- deploy_image "treehouses/privatebin" arm
- deploy_image "treehouses/privatebin" amd64
- deploy_image "treehouses/privatebin" arm64
- timetag=$(date +%Y%m%d%H%M)
- echo $timetag
- tag1="latest"
- tag2=$timetag
- echo $tag2
- create_manifest treehouses/privatebin $tag1 $tag2 treehouses/privatebin-tags:amd64 treehouses/privatebin-tags:arm
  treehouses/privatebin-tags:arm64
- docker manifest inspect treehouses/privatebin:$tag1
- docker manifest inspect treehouses/privatebin:$tag2
deploy:
- provider: script
  script: docker manifest push treehouses/privatebin:$tag1; docker manifest push treehouses/privatebin:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
    - secure: aM0K5RbiyPjDtLuaS0bykAKWlxyvc0u5HCumFso0F0G7MvT3D2j18i2X9PudXdLGKaq1VYoFDoDSXK0uWsuAq409XSUbpuEY5waoWwvwiES3zcgh7qUIZGX2hz4NDlm1WYGFhc6UEwmjD0AAHaFerInavZMZG9Mlb6sGAyOG69w2379Hfq/T8IGOP+VaNFmrhe0JAq5SYVj6y1xPIFB9cCggHwZeFbyZP7dkMZKBKtl/+AUyv/Xjbvq6iGKoJ2Q1CyhUNZuD+kK86KVf0PFSLBbhO1gvaXsMxhpK9MesxcUhjwzYDEE/Lyo1Gz5YYjo/NeQzkgwx5AFLxGmmZNV7yuI5UFFJi/y7lrg8o9CuRir5F2sMAwcvRhL0sOcZ0D++7VoQ+f1toFSjd+XAr0TusobUnWZ0ja3iIk8853UcV1E8R5wJ6OgXhjIyCNgaF3l9PoPTpwI5rnsdhiL5N000wF27Kh1yrue44U72LjlhIiiIJ0WvY3j76n+UuW/Cu1alTwgtVh9ZQ9xTIT/CzCiJyoZa24dgKWsH0X4knRCtkVtIzrzrMq+3cC5wR8e205yGb6Mzdw+G1FXW0wfM0m8wsU8mxHFg+DhXqmG5Ah1KplCIbv2g/z7jKMGjrIM+eWg0kuXgY+kV+e0BZN5yBjer4a71GZQ69X7ZPkRhlQwkznQ=
