name: privatebin-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  privatebin-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses privatebin
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/privatebin"
          base="treehouses/php-apache"
          source .github/workflows/utils.sh
          private_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $private_arm_sha
          base_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $base_arm_sha
          flag_arm=$(is_base "$repo@"$base_arm_sha "$repo@"$private_arm_sha)
          echo $flag_arm
          private_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $private_amd64_sha
          base_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $base_amd64_sha
          flag_amd64=$(is_base "$repo@"$base_amd64_sha "$repo@"$private_amd64_sha)
          echo $flag_amd64
          private_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $private_arm64_sha
          base_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $base_arm64_sha
          flag_arm64=$(is_base "$repo@"$base_arm64_sha "$repo@"$private_arm64_sha)
          echo $flag_arm64
          flag=$(compare "$repo@"$base_arm_sha "$repo@"$private_arm_sha "$repo@"$base_amd64_sha "$repo@"$private_amd64_sha "$repo@"$base_arm64_sha "$repo@"$private_arm64_sha)
          echo $flag
          flag=true
          if [[ $flag == true ]]; then
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            build_image "treehouses/php-apache:latest" arm "$repo"
            build_image "treehouses/php-apache:latest" amd64 "$repo"
            build_image "treehouses/php-apache:latest" arm64 "$repo"
            deploy_image "$repo" arm
            deploy_image "$repo" amd64
            deploy_image "$repo" arm64
            tag=$(date +%Y%m%d%H%M)
            tag2="latest"
            echo $tag
            create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
            docker manifest inspect $repo:$tag
            docker manifest inspect $repo:$tag2
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi
